### ISSUE TITLE
Revisit collection projects visibility

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/SnapSite#61]
- [x] Private projects in public collections should be hidden to anyone but their owner.
- [x] What to do with shared projects added to public collections? @cycomachead any ideas?

**Comment by cycomachead** [comment]
If the shared projects are there, they shouldn't be shown. That makes it too easy to accidentally show someone else's work. 
I *think* that showing shared projects in a collection which is only shared but not published could make sense because the sharing permissions are equivalent. 

Ideally, the sharing settings between all projects in a collection match with the collection, but it would be difficult to guarantee that. In that case, I think what should be presented are only the projects that have the same or more permissive sharing settings. 

(A separate issue, but illustrative of my view, I hope: I would personally expect that if I have a published project in a published collection (say one that i don't manage) that if I make my project private it gets removed from the collection. Otherwise even if I view that collection, and I can still see my own project, it won't necessarily be clear that only I can see it. Maybe having view indicators is enough to solve that issue; there's multiple options there.)

**Comment by bromagosa** [comment]
> I think what should be presented are only the projects that have the same or more permissive sharing settings.

That's what I ended up implementing.

Since this is now in place, there's no point in forbidding users to add private/shared projects to published collections. They can add them, but they'll only be visible to themselves.

**Comment by cycomachead** [comment]
Some additional thoughts I meant to share after some testing...

There are a few edge cases I think we might want to consider - though nothing that's breaking, just things to consider at some point. 

When a project is in a collection but not visible, you've got this weird case where it shows the collection, but then you're not able to remove that project from the collection. 
This makes it hard to tell whether others can see your project in that collection. 

When you add a project to the collection, there's no indication of what the collection settings are, so you can do things that might not make sense.

(This comment has been sitting in this text box for more than a week, oops.)
